export const SET_CURRENT = 'SET_CURRENT';
export const INCOME_SUMMARY = 'INCOME_SUMMARY';
export const TRANSFERS_SUMMARY = 'TRANSFERS_SUMMARY';
export const TRANSFER_MONEY = 'TRANSFER_MONEY';
export const UPDATE_RECIVER_ACC = 'UPDATE_RECIVER_ACC';
export const UPDATE_SENDER_ACC = 'UPDATE_SENDER_ACC';
export const LOGOUT_USER = 'LOGOUT_USER';
